return {
	-- LSP CONFIGS
	require("plugins.lsp.mason"),
	require("plugins.lsp.lspconfig"),
	require("plugins.lsp.cmp"),
	require("plugins.lsp.snippets"),
  require("plugins.lsp.lintern"),
	-- PLUGINS CONFIGURATIONS
	require("plugins.autotag"),
	require("plugins.treesitter"),
	require("plugins.telescope"),
	require("plugins.nvim-tree"),
	require("plugins.which-key"),
	require("plugins.comment-vim"),
	require("plugins.nvim-autopairs"),
	require("plugins.vim-surround"),
	require("plugins.toggleterm"),
	require("plugins.nvim-material-icons"),
	require("plugins.bufferline"),
	require("plugins.lualine"),
	require("plugins.vim_multicursor"),
	require("plugins.dashboard_nvim"),
	require("plugins.rainbow_nvim"),
	require("plugins.colorscheme"),
	require("plugins.trouble"),
  require("plugins.colors"),
  require("plugins.multicursor"),
  require("plugins.bufdel"),
}
